version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: .docker/php/Dockerfile
        container_name: crm-mkl-php
        restart: unless-stopped
        working_dir: /var/www/
        environment:
            - PHP_IDE_CONFIG=serverName=app
        volumes:
            - ./:/var/www
        networks:
            - crm-mkl
        ports:
            - "9000"

    db:
        image: mysql:8.0
        container_name: crm-mkl-db
        environment:
            MYSQL_DATABASE: pingcrm
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_USER: user
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            -   db:/var/lib/mysql
        env_file:
            -   .env
        ports:
            - "3306:3306"
        networks:
            - crm-mkl

    nginx:
        image: nginx:alpine
        container_name: crm-mkl-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - .docker/nginx:/etc/nginx/conf.d/
        networks:
            - crm-mkl

volumes:
    db:
        driver: local

networks:
    crm-mkl:
        driver: bridge
