version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: .docker/php/Dockerfile
        container_name: crm-mkl-php
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - crm-mkl

    db:
        image: mysql:8.0
        container_name: crm-mkl-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        env_file:
            -   .env
        ports:
            - "3306:3306"
        networks:
            - crm-mkl

    nginx:
        image: nginx:alpine
        container_name: crm-mkl-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - .docker/nginx:/etc/nginx/conf.d/
        networks:
            - crm-mkl

networks:
    crm-mkl:
        driver: bridge
